feat(api): 書籍削除・更新用 API を追加
sumiren/bookapp pull request #6
Opened 2022-10-01 07:02 UTC by RikuOta

2022-10-07 13:07 UTC, sumiren requested changes
@RikuOta 
良いと思います！
2点指摘しました！

2022-10-07 13:07 UTC, sumiren commented on backend/src/infra/dynamo-book-store.ts
> +  async deleteBookOfUser(userId: string, bookId: string): Promise<any> {
Promise<void>のほうが良いかと！

2022-10-07 13:07 UTC, sumiren commented on backend/src/infra/dynamo-book-store.ts
> +          item.CreatedAt
これ必要ですか？

2022-10-07 14:46 UTC, RikuOta commented on backend/src/infra/dynamo-book-store.ts
> +          item.CreatedAt
書籍作成日をフロントで使用しているため、必要な認識です。　
より望ましい実装があればご教授ください:bow:

2022-10-07 14:55 UTC, RikuOta commented on backend/src/infra/dynamo-book-store.ts
> +  async deleteBookOfUser(userId: string, bookId: string): Promise<any> {
ご指摘ありがとうございます:bow:
修正しました。
[60c9ad5](https://github.com/sumiren/bookapp/pull/6/commits/60c9ad5a20e46ee615e7da2f0f3d298c8d7776d4)

2022-10-08 05:15 UTC, sumiren requested changes
度々申し訳ありません、修正範囲が1点だけ足りていなかったので確認をお願いできますでしょうか。

2022-10-08 05:15 UTC, sumiren commented on backend/src/infra/dynamo-book-store.ts
> +          item.CreatedAt
読み違えしてました。問題ありません！

2022-10-08 05:15 UTC, sumiren commented on backend/src/presentation/dependency/book-store.ts
> +  deleteBookOfUser(userId: string, bookId: string): Promise<any>;
度々すみません！

インターフェース側も`Promise<void>`に修正したほうがいいですね。
今のコードだと、book-routerからは`Promise<any>`に見えているのではないかと思います。
https://github.com/sumiren/bookapp/pull/6/files#diff-3406359cbee1bc5838098b8ecd72b2dc27452bbb8c716ff60d53697509fb5a8bR55

2022-10-08 06:56 UTC, RikuOta commented on backend/src/presentation/dependency/book-store.ts
> +  deleteBookOfUser(userId: string, bookId: string): Promise<any>;
ありがとうございます:bow:
ご指摘の通りでしたので、修正しました。
[98f83f3](https://github.com/sumiren/bookapp/pull/6/commits/98f83f37feae29835fa2c872698dff290061ca2a)

2022-10-08 08:19 UTC, sumiren commented
LGTM！！

2022-11-03 15:15 UTC, sumiren approved these changes

2022-11-03 15:16 UTC, merged